<#
Strips an old AutoBleem install off a PSC USB stick down to Games/themes/roms and the
console's boot-exploit/RetroBoot layer, so AutoBleem2 can be installed fresh on top.
Also removes macOS junk (.DS_Store, AppleDouble ._* files, .Trashes, .Spotlight-V100, ...)
anywhere on the stick.

Removed (regenerated by rc/backup.sh + backup_internal.sh at next boot, or by AutoBleem2's
installer/first scan - see payload/Autobleem/rc/backup.sh and backup_internal.sh):
  Autobleem/                                  the frontend binary + rc scripts
  System/Bios, Preferences, Databases,        rc/backup.sh does `mkdir -p` + conditional
    Region, Logs, UI                          `cp` for every one of these at every boot
  System/lightguns.txt
  Apps/pscbios/, Apps/abflashkit/             AutoBleem2 ships these two fresh; the rest of
                                               Apps/ (amiberry, doom, ...) is left alone
  retroarch/playlists/AutoBleem.lpl,          AutoBleem-authored playlists; rebuilt by the
    retroarch/playlists/Sony - PlayStation.lpl  next scan

Left alone (besides junk cleanup):
  Games/                                      the actual game library
  themes/                                     UI themes
  roms/                                       AutoBleem2's multi-system RetroArch ROM folders
  retroarch/ (everything but the two playlists above) - RetroBoot's own tree, boot-critical
  028c18a9-ec4b-4632-b2cf-d4e20f252e8f/       the boot-exploit payload - required to boot at all
  anything else not recognized as AutoBleem's own (reported, never touched)

Usage:
  .\clean_autobleem_usb.ps1 -Path F:\ -DryRun      # preview only, changes nothing
  .\clean_autobleem_usb.ps1 -Path F:\ -Execute      # actually deletes

Optional overrides (all default to the behavior described above):
  -KeepApps                  leave all of Apps/ as-is, including pscbios/abflashkit (junk-clean only)
  -RemoveAllApps              delete the whole Apps/ folder, not just pscbios/ and abflashkit/
  -RemoveRetroArchTree        delete the whole retroarch/ tree instead of just its two playlists
  -KeepAutobleemPlaylists      leave retroarch/playlists/AutoBleem.lpl and Sony - PlayStation.lpl alone
  -RemoveBootExploit          also delete 028c18a9-ec4b-4632-b2cf-d4e20f252e8f/ (you'll need to redo the jailbreak)
#>

[CmdletBinding(DefaultParameterSetName = 'DryRun')]
param(
    [Parameter(Mandatory = $true)]
    [string]$Path,

    [Parameter(Mandatory = $true, ParameterSetName = 'DryRun')]
    [switch]$DryRun,

    [Parameter(Mandatory = $true, ParameterSetName = 'Execute')]
    [switch]$Execute,

    [switch]$KeepApps,
    [switch]$RemoveAllApps,
    [switch]$RemoveRetroArchTree,
    [switch]$KeepAutobleemPlaylists,
    [switch]$RemoveBootExploit
)

$ErrorActionPreference = 'Stop'

$root = (Resolve-Path -LiteralPath $Path).ProviderPath.TrimEnd('\', '/')
if (-not (Test-Path -LiteralPath $root -PathType Container)) {
    throw "Not a directory: $root"
}

$isDryRun = -not $Execute.IsPresent

Write-Host "Target: $root"
Write-Host $(if ($isDryRun) { "Mode:   DRY RUN - nothing will be deleted" } else { "Mode:   EXECUTE - files will be permanently deleted" })
Write-Host ""

# ---- stats -----------------------------------------------------------------

$stats = [ordered]@{
    'macOS junk'                 = @{ count = 0; bytes = 0L }
    'Autobleem/'                 = @{ count = 0; bytes = 0L }
    'System backup dirs'         = @{ count = 0; bytes = 0L }
    'System/lightguns.txt'       = @{ count = 0; bytes = 0L }
    'Apps/ (whole folder)'       = @{ count = 0; bytes = 0L }
    'Apps/pscbios + abflashkit'  = @{ count = 0; bytes = 0L }
    'AutoBleem playlists'        = @{ count = 0; bytes = 0L }
    'retroarch/ (whole tree)'    = @{ count = 0; bytes = 0L }
    'boot-exploit folder'        = @{ count = 0; bytes = 0L }
}

function Get-PathSize([string]$p) {
    if (Test-Path -LiteralPath $p -PathType Leaf) {
        return (Get-Item -LiteralPath $p -Force).Length
    }
    if (Test-Path -LiteralPath $p -PathType Container) {
        $sum = (Get-ChildItem -LiteralPath $p -Recurse -Force -File -ErrorAction SilentlyContinue |
                Measure-Object -Property Length -Sum).Sum
        if ($null -eq $sum) { return 0L }
        return $sum
    }
    return 0L
}

function Remove-Tracked([string]$p, [string]$category, [string]$reason) {
    if (-not (Test-Path -LiteralPath $p)) { return }
    $size = Get-PathSize $p
    $stats[$category].count += 1
    $stats[$category].bytes += $size
    if ($isDryRun) {
        Write-Host "[DRYRUN] would remove ($category): $p  -- $reason"
    }
    else {
        Write-Host "removing ($category): $p"
        try {
            Remove-Item -LiteralPath $p -Recurse -Force -ErrorAction Stop
        }
        catch {
            Write-Warning "failed to remove '$p': $_"
        }
    }
}

# ---- 1. macOS junk, anywhere on the stick -----------------------------------

$junkDirNames = @('.Trashes', '.Spotlight-V100', '.TemporaryItems', '.fseventsd', '.apdisk', '.DocumentRevisions-V100')
$junkFileNames = @('.DS_Store', '.VolumeIcon.icns', '.com.apple.timemachine.supported')

Write-Host "--- scanning for macOS junk (this walks the whole tree, can take a while on a big stick) ---"
$junkItems = Get-ChildItem -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue | Where-Object {
    ($_.PSIsContainer -and ($junkDirNames -contains $_.Name)) -or
    (-not $_.PSIsContainer -and (($junkFileNames -contains $_.Name) -or ($_.Name -like '._*')))
}

# shortest paths first, so removing a junk directory doesn't error on already-gone children
$junkItems = $junkItems | Sort-Object { $_.FullName.Length }

foreach ($item in $junkItems) {
    if (-not (Test-Path -LiteralPath $item.FullName)) { continue } # already removed as part of a parent dir
    Remove-Tracked $item.FullName 'macOS junk' 'macOS metadata, not part of AutoBleem or your games'
}

# ---- 2. Autobleem/ (the frontend itself) ------------------------------------

Remove-Tracked (Join-Path $root 'Autobleem') 'Autobleem/' 'old frontend binary + rc scripts; AutoBleem2 installs fresh'

# ---- 3. System/ backup + database directories --------------------------------
# rc/backup.sh does `mkdir -p` and a guarded `cp` for every one of these at every
# boot, and backup_internal.sh regenerates internal.db from /gaadata the same way.

foreach ($name in @('Bios', 'Preferences', 'Databases', 'Region', 'Logs', 'UI')) {
    Remove-Tracked (Join-Path $root "System\$name") 'System backup dirs' 'recreated from the console (/gaadata, /data) at next boot'
}
Remove-Tracked (Join-Path $root 'System\lightguns.txt') 'System/lightguns.txt' 'regenerated as light-gun games are flagged again'

# ---- 4. Apps/ ----------------------------------------------------------------
# Default: only the two AutoBleem2 ships fresh (pscbios, abflashkit). The rest of Apps/
# (amiberry, doom, eduke32, ...) is third-party/bundled content, left as-is by default.

if ($KeepApps) {
    Write-Host "[skip] Apps/ kept entirely (per -KeepApps)"
}
elseif ($RemoveAllApps) {
    Remove-Tracked (Join-Path $root 'Apps') 'Apps/ (whole folder)' 'old bundled/third-party apps; removed per -RemoveAllApps'
}
else {
    Remove-Tracked (Join-Path $root 'Apps\pscbios') 'Apps/pscbios + abflashkit' 'AutoBleem2 ships this fresh'
    Remove-Tracked (Join-Path $root 'Apps\abflashkit') 'Apps/pscbios + abflashkit' 'AutoBleem2 ships this fresh'
}

# ---- 5. retroarch/ ------------------------------------------------------------

if ($RemoveRetroArchTree) {
    Remove-Tracked (Join-Path $root 'retroarch') 'retroarch/ (whole tree)' 'removed per -RemoveRetroArchTree'
}
elseif (-not $KeepAutobleemPlaylists) {
    Remove-Tracked (Join-Path $root 'retroarch\playlists\AutoBleem.lpl') 'AutoBleem playlists' 'rebuilt by AutoBleem2''s next scan'
    Remove-Tracked (Join-Path $root 'retroarch\playlists\Sony - PlayStation.lpl') 'AutoBleem playlists' 'rebuilt by AutoBleem2''s next scan'
}
else {
    Write-Host "[skip] retroarch/ kept untouched (per -KeepAutobleemPlaylists)"
}

# ---- 6. boot-exploit payload folder -------------------------------------------

if ($RemoveBootExploit) {
    $exploitDir = Get-ChildItem -LiteralPath $root -Directory -Force -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' }
    foreach ($d in $exploitDir) {
        Remove-Tracked $d.FullName 'boot-exploit folder' 'removed per -RemoveBootExploit; jailbreak must be redone'
    }
}
else {
    Write-Host "[skip] boot-exploit folder kept (needed to boot at all)"
}

# ---- unrecognized top-level items: report only, never touched ----------------

$known = @('Autobleem', 'Apps', 'System', 'Games', 'themes', 'roms', 'retroarch') +
    @((Get-ChildItem -LiteralPath $root -Directory -Force -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' }).Name)

$unrecognized = Get-ChildItem -LiteralPath $root -Force -ErrorAction SilentlyContinue | Where-Object {
    ($known -notcontains $_.Name) -and
    -not ($_.PSIsContainer -and ($junkDirNames -contains $_.Name)) -and
    -not (-not $_.PSIsContainer -and (($junkFileNames -contains $_.Name) -or ($_.Name -like '._*')))
}

if ($unrecognized) {
    Write-Host ""
    Write-Host "--- unrecognized top-level items (left completely untouched) ---"
    foreach ($u in $unrecognized) { Write-Host "  $($u.FullName)" }
}

# ---- summary -------------------------------------------------------------------

Write-Host ""
Write-Host "=== summary ==="
$totalBytes = 0L
$totalCount = 0
foreach ($key in $stats.Keys) {
    $c = $stats[$key].count
    $b = $stats[$key].bytes
    if ($c -gt 0) {
        "{0,-28} {1,6} item(s)   {2,10:N2} MB" -f $key, $c, ($b / 1MB) | Write-Host
        $totalBytes += $b
        $totalCount += $c
    }
}
Write-Host "-------------------------------------------------------"
"{0,-28} {1,6} item(s)   {2,10:N2} MB" -f 'TOTAL', $totalCount, ($totalBytes / 1MB) | Write-Host

if ($isDryRun) {
    Write-Host ""
    Write-Host "Dry run only - nothing was deleted. Re-run with -Execute to apply."
}
